In [39]:
import torch

In [40]:
# 1. Создайте случайный FloatTensor размера 3x4x5
a = torch.randn(3, 4, 5).type(torch.FloatTensor)
a

tensor([[[-0.2982,  1.4221,  0.1733,  0.7573,  1.1696],
         [ 1.1827, -1.3697, -0.8046, -0.7592,  1.6927],
         [-0.4979,  0.4758, -0.6725, -0.2170, -0.8721],
         [-1.3490,  0.8947,  0.7508, -0.2387, -0.8914]],

        [[ 0.0700, -2.7807, -0.4703, -0.1492,  0.5418],
         [-1.8742,  0.1525,  1.1902, -0.1721, -0.4812],
         [-0.9880,  0.7646, -0.4185, -0.3852,  1.6585],
         [-0.6077, -0.0124,  0.5613,  0.0734, -1.5077]],

        [[ 0.7984, -1.7426,  0.5308, -0.2410,  0.3191],
         [ 0.4287, -0.3175,  0.1111, -0.8965, -2.1413],
         [ 0.5859,  0.0417, -0.3735,  0.2330,  1.0692],
         [ 0.2959, -1.4343, -0.2984,  1.6235, -1.3917]]])

In [41]:
# 2. Выведите его форму (shape)
a.shape

torch.Size([3, 4, 5])

In [46]:
# 3. Приведите его к форме 6х10
a.resize_(6, 10)

tensor([[-0.2982,  1.4221,  0.1733,  0.7573,  1.1696,  1.1827, -1.3697, -0.8046,
         -0.7592,  1.6927],
        [-0.4979,  0.4758, -0.6725, -0.2170, -0.8721, -1.3490,  0.8947,  0.7508,
         -0.2387, -0.8914],
        [ 0.0700, -2.7807, -0.4703, -0.1492,  0.5418, -1.8742,  0.1525,  1.1902,
         -0.1721, -0.4812],
        [-0.9880,  0.7646, -0.4185, -0.3852,  1.6585, -0.6077, -0.0124,  0.5613,
          0.0734, -1.5077],
        [ 0.7984, -1.7426,  0.5308, -0.2410,  0.3191,  0.4287, -0.3175,  0.1111,
         -0.8965, -2.1413],
        [ 0.5859,  0.0417, -0.3735,  0.2330,  1.0692,  0.2959, -1.4343, -0.2984,
          1.6235, -1.3917]])

In [47]:
# 4. Создайте случайный IntTensor размера 10
b = torch.randint(10, size=(10, 1)).type(torch.IntTensor)
b

tensor([[2],
        [3],
        [7],
        [9],
        [6],
        [7],
        [7],
        [2],
        [2],
        [8]], dtype=torch.int32)

In [48]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
a * b.T


tensor([[ -0.5964,   4.2664,   1.2131,   6.8156,   7.0178,   8.2790,  -9.5881,
          -1.6091,  -1.5184,  13.5415],
        [ -0.9959,   1.4275,  -4.7076,  -1.9529,  -5.2325,  -9.4433,   6.2632,
           1.5017,  -0.4775,  -7.1310],
        [  0.1400,  -8.3422,  -3.2924,  -1.3430,   3.2506, -13.1194,   1.0672,
           2.3805,  -0.3441,  -3.8497],
        [ -1.9759,   2.2938,  -2.9292,  -3.4666,   9.9508,  -4.2539,  -0.0868,
           1.1225,   0.1468, -12.0613],
        [  1.5967,  -5.2277,   3.7159,  -2.1689,   1.9146,   3.0006,  -2.2228,
           0.2222,  -1.7930, -17.1301],
        [  1.1717,   0.1252,  -2.6145,   2.0973,   6.4153,   2.0714, -10.0401,
          -0.5968,   3.2470, -11.1336]])

In [49]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти
a @ a.T

tensor([[11.4468, -5.2285, -7.6033, -0.8035, -4.5248,  0.2134],
        [-5.2285,  5.7701,  2.5467,  2.3309, -0.4660, -2.0574],
        [-7.6033,  2.5467, 13.4880,  1.4755,  5.3257, -0.0930],
        [-0.8035,  2.3309,  1.4755,  7.5976,  1.2470,  3.1808],
        [-4.5248, -0.4660,  5.3257,  1.2470,  9.8013,  2.5554],
        [ 0.2134, -2.0574, -0.0930,  3.1808,  2.5554,  8.4884]])

In [57]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.tensor([1.0], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.0], requires_grad=True)


y = x**3 + z - 75 * t

y.backward()
x.grad, z.grad, t.grad

(tensor([3.]), tensor([1.]), tensor([-75.]))

In [58]:
# 8. Создайте единичный тензор размера 5x6
c = torch.ones(5, 6)
c

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [59]:
# 9. Переведите его в формат numpy
c.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)